Footer and carousel unit test
Ne-anna/renome-next.js pull request #10
Opened 2022-08-11 08:12 UTC by Ne-anna

In this PR I have created test file for footer, because it was similarly created as gallery.test.tsx file I  decided to not create separate PR, but combine it together with carousel test.
In carousel.test.tsx file I have test block which tests title and subtitle, test block which tests button with added testId, and I tried to test if button is clicked.
Issue: Even if I tested both buttons my test coverage is lower then I expected.

2022-08-11 09:11 UTC, uldiszigurs requested changes

2022-08-11 09:11 UTC, uldiszigurs commented on pages/atoms/carousel-next-button/carousel-next-button.tsx
> +      data-testid="buttonNext"
rule of thumb is to use data-testid as last resort, you could add aria-label e.g. 'previous' and then use getByRole('button', {name: 'previous'} )
also afaik for buttons, the aria label / button name is determined by the text content between the button tags, this case there is image which doesnt have any text, using getByRole would solve this accessibility issue too

2022-08-11 09:11 UTC, uldiszigurs commented on pages/atoms/carousel-previous-button/carousel-previous-button.tsx
> +      data-testid="buttonPrevious"
as previously, preferably avoid data-testid, it is also rendered to the DOM

2022-08-11 09:11 UTC, uldiszigurs commented on pages/organisms/carousel/carousel.test.tsx
> +it("Is 'previous' button clicked?", () => {
duplicate test name, can mess with u if test fails

2022-08-15 07:07 UTC, uldiszigurs approved these changes

2022-08-15 07:59 UTC, ilze-dom approved these changes

2022-08-15 08:30 UTC, ilze-dom commented on pages/organisms/carousel/carousel.test.tsx
> +  // loadPreviousSlide(): void {},
could use jest.fn() here

2022-08-15 08:33 UTC, ilze-dom approved these changes

2022-08-15 08:34 UTC, merged